import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import product from "../data/data"
import Products from '../componnents/products'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Next shop</a>
        </h1>

        <p className={styles.description}>
        Products
        </p>

        <div className={styles.grid}>
        <Products/>
         

         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
             MhdRezaei
          </span>
        </a>
      </footer>
    </div>
  )
}
