import fs from "fs/promises"
import path from "path"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Products from '../componnents/products'
import Link from 'next/link'
export default function Home(props) {
  const {products} = props
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Next shop</a>
        </h1>

        <p className={styles.description}>
        Products
        </p>

        <div className={styles.grid}>
        <Products items={products}/>
         

         
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="/"
        >
        <div>
          Powered by{' '}
          <span className={styles.logo}>
             MhdRezaei
          </span>
          </div>
        </Link>
      </footer>
    </div>
  )
}

export async function getStaticProps(){
  const dataPath = path.join(process.cwd(), 'data' , 'data.json');
  const product = await fs.readFile(dataPath);
  const productList = JSON.parse(product);
  console.log(productList)

  return {
      props :{
          products : productList.products
      }
  }
}